"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Plus, Link as LinkIcon, ExternalLink, MessageCircle, FileVideo, Image as ImageIcon, FileText, Loader2, Check, Layout, Layers, X } from "lucide-react";
import { deliverableService } from "@/lib/deliverables";
import { clientService } from "@/lib/clients";
import { Deliverable, DeliverableType } from "@/types/deliverables";
import Link from "next/link";
import { useAuth } from "@/components/providers/AuthProvider";

export default function DeliverablesPage() {
    const { user } = useAuth();
    const [items, setItems] = useState<Deliverable[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isCreating, setIsCreating] = useState(false);

    // New Item Form State
    const [newItem, setNewItem] = useState({
        title: "",
        clientName: "",
        clientId: "",
        type: "image" as DeliverableType,
        url: "",
        carouselSlides: ["", ""], // For carousel type
        description: ""
    });

    useEffect(() => {
        loadItems();
        // Sync clients from API on load to ensure list is fresh
        clientService.syncFromAPI().catch(console.error);
    }, []);

    const loadItems = async () => {
        const data = await deliverableService.getAll();
        setItems(data);
        setIsLoading(false);
    };

    const handleCreate = async () => {
        const primaryUrl = newItem.type === 'carousel' ? newItem.carouselSlides[0] : newItem.url;

        if (!newItem.title || !primaryUrl) {
            alert("Título y URL principal son obligatorios");
            return;
        }

        if (!newItem.clientId) {
            alert("Debes seleccionar un cliente");
            return;
        }

        setIsCreating(true);

        const deliverable: Deliverable = {
            id: "", // ID generated by Backend
            title: newItem.title,
            clientName: newItem.clientName || "Cliente General",
            clientId: newItem.clientId,
            type: newItem.type,
            url: primaryUrl,
            carouselUrls: newItem.type === 'carousel' ? newItem.carouselSlides.slice(1).filter(u => u.trim() !== "") : undefined,
            status: "pending",
            createdAt: new Date().toISOString(),
            description: newItem.description
        };

        const newId = await deliverableService.add(deliverable);

        if (newId) {
            loadItems();
            setIsCreating(false);

            // Reset form
            setNewItem({
                title: "", clientName: "", clientId: "",
                type: "image", url: "", carouselSlides: ["", ""], description: ""
            });

            // Portal Assignment Success Message
            const selectedClient = clientService.getById(deliverable.clientId || "");
            alert(`✅ ¡Entregable asignado correctamente!\n\nYa está visible en el portal de ${selectedClient?.name || 'Cliente'}.`);
        } else {
            alert("Error al guardar en ERPNext. Revisa la consola.");
            setIsCreating(false);
        }
    };

    const copyLink = (id: string) => {
        const link = `${window.location.origin}/review/${id}`;
        navigator.clipboard.writeText(link);
        alert("Link copiado al portapapeles: " + link);
    };

    const getTypeIcon = (type: DeliverableType) => {
        switch (type) {
            case 'video': return <FileVideo className="w-5 h-5 text-blue-500" />;
            case 'image': return <ImageIcon className="w-5 h-5 text-purple-500" />;
            case 'carousel': return <Layers className="w-5 h-5 text-pink-500" />;
            default: return <FileText className="w-5 h-5 text-gray-500" />;
        }
    };

    const getStatusBadge = (status: string) => {
        switch (status) {
            case 'approved':
                return <span className="px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-700 flex items-center gap-1"><Check className="w-3 h-3" /> Aprobado</span>;
            case 'changes_requested':
                return <span className="px-2 py-1 rounded-full text-xs font-medium bg-red-100 text-red-700 flex items-center gap-1"><MessageCircle className="w-3 h-3" /> Cambios</span>;
            default:
                return <span className="px-2 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-700">Pendiente</span>;
        }
    };

    const updateCarouselSlide = (index: number, value: string) => {
        const slides = [...newItem.carouselSlides];
        slides[index] = value;
        setNewItem({ ...newItem, carouselSlides: slides });
    };

    const addCarouselSlide = () => {
        setNewItem({ ...newItem, carouselSlides: [...newItem.carouselSlides, ""] });
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Entregables & Aprobaciones</h1>
                    <p className="text-gray-500 text-sm">Gestiona los entregables visibles en el portal del cliente.</p>
                </div>
                <Button onClick={() => window.scrollTo({ top: 9999, behavior: 'smooth' })} className="bg-lumen-priority hover:bg-lumen-priority/90 text-white">
                    <Plus className="w-4 h-4 mr-2" />
                    Nuevo Entregable
                </Button>
            </div>

            {/* List */}
            <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="bg-gray-50 text-gray-500 font-medium border-b border-gray-200">
                            <tr>
                                <th className="px-6 py-3">Entregable</th>
                                <th className="px-6 py-3">Cliente</th>
                                <th className="px-6 py-3">Estado</th>
                                <th className="px-6 py-3 text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                            {isLoading ? (
                                <tr><td colSpan={4} className="p-8 text-center text-gray-400">Cargando...</td></tr>
                            ) : items.map((item) => (
                                <tr key={item.id} className="hover:bg-gray-50 transition-colors">
                                    <td className="px-6 py-4">
                                        <div className="flex items-center gap-3">
                                            <div className="p-2 bg-gray-100 rounded-lg">
                                                {getTypeIcon(item.type)}
                                            </div>
                                            <div>
                                                <p className="font-medium text-gray-900">{item.title}</p>
                                                <div className="flex items-center gap-2">
                                                    <span className="text-xs text-gray-500">{new Date(item.createdAt).toLocaleDateString()}</span>
                                                    {item.type === 'carousel' && (
                                                        <span className="text-xs bg-pink-50 text-pink-600 px-1.5 rounded border border-pink-100">Carrusel</span>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                        {item.status === 'changes_requested' && item.feedback && (
                                            <div className="mt-2 text-xs bg-red-50 text-red-600 p-2 rounded border border-red-100 max-w-xs">
                                                <strong>Feedback:</strong> "{item.feedback[item.feedback.length - 1].comment}"
                                            </div>
                                        )}
                                    </td>
                                    <td className="px-6 py-4 text-gray-600">{item.clientName}</td>
                                    <td className="px-6 py-4">{getStatusBadge(item.status)}</td>
                                    <td className="px-6 py-4 text-right space-x-2">
                                        <Link href={`/review/${item.id}`} target="_blank">
                                            <Button variant="ghost" size="sm" title="Ver Link Individual">
                                                <ExternalLink className="w-4 h-4 text-gray-400" />
                                            </Button>
                                        </Link>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Creation Form */}
            <div className="bg-gray-50 p-6 rounded-xl border border-gray-200 mt-8">
                <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                    <Layout className="w-5 h-5 text-lumen-priority" />
                    Asignar Nuevo Entregable al Portal
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-4 md:col-span-2">
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div className="md:col-span-1">
                                <label className="block text-sm font-medium text-gray-700 mb-1">Cliente *</label>
                                <select
                                    className="p-2.5 rounded-lg border border-gray-300 w-full bg-white text-sm"
                                    value={newItem.clientId}
                                    onChange={e => {
                                        const selectedClient = clientService.getById(e.target.value);
                                        if (selectedClient) {
                                            setNewItem({ ...newItem, clientName: selectedClient.name, clientId: selectedClient.id });
                                        } else {
                                            setNewItem({ ...newItem, clientName: "", clientId: "" });
                                        }
                                    }}
                                >
                                    <option value="">-- Seleccionar Cliente --</option>
                                    {clientService.getAll().map(c => (
                                        <option key={c.id} value={c.id}>{c.name}</option>
                                    ))}
                                </select>
                            </div>
                            <div className="md:col-span-1">
                                <label className="block text-sm font-medium text-gray-700 mb-1">Tipo de Contenido</label>
                                <select
                                    className="p-2.5 rounded-lg border border-gray-300 w-full bg-white text-sm"
                                    value={newItem.type}
                                    onChange={e => setNewItem({ ...newItem, type: e.target.value as DeliverableType })}
                                >
                                    <option value="image">Imagen</option>
                                    <option value="video">Video</option>
                                    <option value="carousel">Carrusel (Múltiples Img)</option>
                                    <option value="link">Enlace Externo</option>
                                </select>
                            </div>
                            <div className="md:col-span-1">
                                <label className="block text-sm font-medium text-gray-700 mb-1">Título *</label>
                                <input
                                    type="text"
                                    placeholder="Ej. Reel de Lanzamiento"
                                    className="p-2.5 rounded-lg border border-gray-300 w-full text-sm"
                                    value={newItem.title}
                                    onChange={e => setNewItem({ ...newItem, title: e.target.value })}
                                />
                            </div>
                        </div>
                    </div>

                    <div className="md:col-span-2">
                        {newItem.type === 'carousel' ? (
                            <div className="space-y-3 bg-white p-4 rounded-lg border border-gray-200">
                                <label className="block text-sm font-medium text-gray-700">Imágenes del Carrusel</label>
                                {newItem.carouselSlides.map((slide, idx) => (
                                    <div key={idx} className="flex gap-2">
                                        <span className="text-sm text-gray-500 py-2.5 w-6">{idx + 1}.</span>
                                        <input
                                            type="text"
                                            placeholder={`URL de la imagen ${idx + 1}`}
                                            className="flex-1 p-2.5 rounded-lg border border-gray-300 text-sm"
                                            value={slide}
                                            onChange={e => updateCarouselSlide(idx, e.target.value)}
                                        />
                                        {idx > 1 && (
                                            <Button variant="ghost" size="icon" onClick={() => {
                                                const newSlides = newItem.carouselSlides.filter((_, i) => i !== idx);
                                                setNewItem({ ...newItem, carouselSlides: newSlides });
                                            }}>
                                                <X className="w-4 h-4" />
                                            </Button>
                                        )}
                                    </div>
                                ))}
                                <Button variant="outline" size="sm" onClick={addCarouselSlide} className="mt-2 text-lumen-priority border-lumen-priority/20">
                                    <Plus className="w-3 h-3 mr-1" /> Agregar Slide
                                </Button>
                            </div>
                        ) : (
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">URL del Contenido *</label>
                                <input
                                    type="text"
                                    placeholder={newItem.type === 'video' ? "https://youtube.com/..." : "https://..."}
                                    className="p-2.5 rounded-lg border border-gray-300 w-full text-sm"
                                    value={newItem.url}
                                    onChange={e => setNewItem({ ...newItem, url: e.target.value })}
                                />
                                <p className="text-xs text-gray-500 mt-1">Pega el link directo a la imagen o video.</p>
                            </div>
                        )}
                    </div>

                    <div className="md:col-span-2">
                        <label className="block text-sm font-medium text-gray-700 mb-1">Descripción / Mensaje</label>
                        <textarea
                            placeholder="Notas para el cliente sobre esta entrega..."
                            className="p-2.5 rounded-lg border border-gray-300 w-full text-sm h-24"
                            value={newItem.description}
                            onChange={e => setNewItem({ ...newItem, description: e.target.value })}
                        />
                    </div>
                </div>
                <div className="mt-6 flex justify-end">
                    <Button onClick={handleCreate} disabled={isCreating} className="bg-lumen-priority text-white px-8">
                        {isCreating ? <Loader2 className="animate-spin w-4 h-4 mr-2" /> : <Layout className="w-4 h-4 mr-2" />}
                        {isCreating ? "Guardando..." : "Asignar a Portal"}
                    </Button>
                </div>
            </div>
        </div>
    );
}
