"use client";

import { Deliverable, MOCK_DELIVERABLES, DeliverableStatus, DeliverableFeedback } from "@/types/deliverables";

const STORAGE_KEY = 'lumen_deliverables_v1';

export const deliverableService = {
    getAll: async (): Promise<Deliverable[]> => {
        try {
            const res = await fetch('/api/erp/deliverables');
            if (res.ok) return await res.json();
            return [];
        } catch (e) {
            console.error("Error fetching deliverables", e);
            return [];
        }
    },

    getById: async (id: string): Promise<Deliverable | undefined> => {
        try {
            const res = await fetch(`/api/erp/deliverables/${id}`);
            if (res.ok) return await res.json();
            return undefined;
        } catch (e) {
            return undefined;
        }
    },

    add: async (item: Deliverable): Promise<string | null> => {
        try {
            const res = await fetch('/api/erp/deliverables', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(item)
            });
            const data = await res.json();
            return data.id || null;
        } catch (e) {
            console.error("Error creating deliverable", e);
            return null;
        }
    },

    updateStatus: async (id: string, status: DeliverableStatus, feedback?: DeliverableFeedback) => {
        try {
            await fetch(`/api/erp/deliverables/${id}`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ status, feedback })
            });
        } catch (e) {
            console.error("Error updating status", e);
        }
    },

    createId: () => {
        // ID is now generated by backend, but we keep this for temp local usage if needed, 
        // though strictly we should ignore it in add()
        return '';
    },

    getByClientId: async (clientId: string): Promise<Deliverable[]> => {
        try {
            const res = await fetch(`/api/erp/deliverables?clientId=${clientId}`);
            if (res.ok) return await res.json();
            return [];
        } catch (e) {
            return [];
        }
    }
};
